<div id="gkurumsal">
<div id="kurum">
<h1>Gizlilik Sözleşmesi</h1>
<p>

Bu beyan zerO'clock’nın gizlilik politikasını içerir. zerO'clock web sitesini ziyaret ederek aşağıdaki şartları ve kuralları uygulamayı kabul etmiş sayılmaktasınız.
zerO'clock üyelik aşamasında ve daha sonrasında sizden bazı kişisel bilgilerinizi talep eder. Kişisel bilgilerinizin korunması ve gizliliğinizin sürdürülebilmesi, zerO'clock ekibi olarak birinci önceliğimizdir. Bu nedenle vermiş olduğunuz bilgiler, Üyelik Sözleşmesi’nde belirtilen kurallar ve amaçlar dışında herhangi bir kapsamda kullanılmayacak, üçüncü şahıslarla paylaşılmayacaktır.

Sistemle ilgili sorunların tespiti ve söz konusu sorunların en hızlı şekilde giderilebilmesi için, zerO'clock gerektiğinde kullanıcıların IP adresini tespit etmekte ve bunu kullanmaktadır. IP adresleri, kullanıcıları genel bir şekilde tanımlamak ve kapsamlı demografik bilgi toplamak amacıyla da kullanılabilir. Sitemizdeki kayıt formları, sipariş formları, anketler ve yarışmalarda, irtibat bilgilerinizi (adınız, soyadınız, e-mail adresiniz, telefon numaralarınız ve posta adresiniz) vermeniz talep edilmektedir. Ayrıca, satın alma formunda kredi kartı bilgilerinizi vermeniz gerekmektedir. Yukarıda bahsedilen kişisel bilgileriniz; siparişlerinizi almak, ürün ve hizmetlerimizi sunmak, ödemelerinizi gerçekleştirmek, siparişlerinizi ulaştırmak ve siparişleriniz ile ilgili bilgi vermek, ürünler ve hizmetler hakkında pazarlama amacıyla sizinle irtibata geçmek, bilgilerinizi güncellemek, üyeliğinizi yönetmek ve sürdürmek, ilginizi çekebilecek ürün ve hizmetleri önermek ve 3. şahısların teknik, lojistik ve benzeri diğer işlevlerini bizim adımıza yerine getirmelerini sağlamak amacıyla kullanılmaktadır.

zerO'clock üyesi olduğunuz andan itibaren, aksi tarafınızdan talep edilmediği sürece, günlük ve haftalık bilgilendirme e-mailleri, e-mail adresinize gönderilecektir. Dilediğiniz zaman bu e-maillerle ilgili değişiklik yapma, hizmetten vazgeçme ve yeniden başlatma hakkınız bulunmaktadır. Bu e-maillerin içeriği; satın almış olduğunuz ürün veya ürünlerle ilgili bilgiler, ilgileneceğinizi düşündüğümüz diğer ürünler, 3. kişilerin reklamlarını ve benzeri bilgileri içerebilir. Demografik bilgiler, sitemizi kullanıcılarımızın ilgi alanlarına göre uyarlamak için kullanılmaktadır. Bu bilgiler, reklamların hedef kitleye uyarlanabilmesini temin etmek maksadıyla ve yalnızca diğer kullanıcılara ait bilgilerle birlikte olmak üzere, reklam verenlerle paylaşılabilir. Bu bilgilerde herhangi bir şekilde kişisel bilgi verilmez, sadece grup olarak kullanıcı eğilimleri ile ilgili bir takım çıkarımlar yapmak ve segmentasyon amacıyla kullanılır. Toplanan mali bilgiler satın aldığınız ürün ve hizmetleri size fatura etmek için kullanılmaktadır. Sitemizde bir satın alma yaptığınızda size ait mali bilgilerin, işleminizi gerçekleştirmek için gerekli 3. şahıslara (bankalar, kredi kartı şirketleri vb.) verilmesini kabul etmektesiniz. Paylaşılacak bilgiler; kredi kartı numarası, son kullanma tarihi, CVV2 de dahil olmak üzere gerekli tüm mali bilgileri içerir.

Tüm kredi kartı ve kişisel bilgileriniz, internet güvenlik standardı olan SSL Secure sistemi ile 128 mbit şifrelenmiştir. Bu şekilde, internet üzerindeki dolaşımları sırasında herhangi bir şekilde bu bilgilerinizin istenilmeyen kişi veya kurumlar tarafından ele geçirilmesi önlenmiştir. Gizlilik politikamız ile ilgili her türlü soru ve öneriniz için sitemizdeki iletişim bölümünden bize e-mail gönderebilirsiniz. zerO'clock üyelik iptal işleminizi info@zerO'clock.com adresine e-mail göndererek veya zerO'clock‘Hesabım’ sekmesi altında yer alan ‘Üyelik İptali’ seçeneği üzerinden işlem yaparak gerçekleştirebilirsiniz.

</div>
</div>